// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFCQohnLaVyYJz2gVUQ-Yw2K1m4XBfCBo',
    appId: '1:744951945641:web:4311f49caa469a4634ccb8',
    messagingSenderId: '744951945641',
    projectId: 'mynotes-flutter-cunam',
    authDomain: 'mynotes-flutter-cunam.firebaseapp.com',
    storageBucket: 'mynotes-flutter-cunam.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA31b7TbMz8uoY0PrxSCjuZmtOSduo5mj0',
    appId: '1:744951945641:android:54e61180d086436d34ccb8',
    messagingSenderId: '744951945641',
    projectId: 'mynotes-flutter-cunam',
    storageBucket: 'mynotes-flutter-cunam.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDI4djZSMqotVcGp-c8mUI-m_3rjm9N8X4',
    appId: '1:744951945641:ios:43ee968b18f494e034ccb8',
    messagingSenderId: '744951945641',
    projectId: 'mynotes-flutter-cunam',
    storageBucket: 'mynotes-flutter-cunam.appspot.com',
    iosBundleId: 'com.cunam.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDI4djZSMqotVcGp-c8mUI-m_3rjm9N8X4',
    appId: '1:744951945641:ios:6e80b3a85bb450dd34ccb8',
    messagingSenderId: '744951945641',
    projectId: 'mynotes-flutter-cunam',
    storageBucket: 'mynotes-flutter-cunam.appspot.com',
    iosBundleId: 'com.cunam.mynotes.RunnerTests',
  );
}
